name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodule
        uses: actions/checkout@v2.3.5
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: "14.x"
      - name: Installing my packages
        run: npm ci
      - name: Build my App
        run: npm run build && npm run export && touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
